/**
 * Copyright 2023 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { parseRawData } from '../src/parser';

const demoData = JSON.parse(`{
  "url": "https://api.github.com/repos/umihico/docker-selenium-lambda/pulls/176",
  "id": 1387395129,
  "node_id": "PR_kwDOFK3xYM5Ssfg5",
  "html_url": "https://github.com/umihico/docker-selenium-lambda/pull/176",
  "diff_url": "https://github.com/umihico/docker-selenium-lambda/pull/176.diff",
  "patch_url": "https://github.com/umihico/docker-selenium-lambda/pull/176.patch",
  "issue_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/issues/176",
  "number": 176,
  "state": "closed",
  "locked": false,
  "title": "Add demo-test GitHub action",
  "user": {
    "login": "umihico",
    "id": 39179585,
    "node_id": "MDQ6VXNlcjM5MTc5NTg1",
    "avatar_url": "https://avatars.githubusercontent.com/u/39179585?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/umihico",
    "html_url": "https://github.com/umihico",
    "followers_url": "https://api.github.com/users/umihico/followers",
    "following_url": "https://api.github.com/users/umihico/following{/other_user}",
    "gists_url": "https://api.github.com/users/umihico/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/umihico/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/umihico/subscriptions",
    "organizations_url": "https://api.github.com/users/umihico/orgs",
    "repos_url": "https://api.github.com/users/umihico/repos",
    "events_url": "https://api.github.com/users/umihico/events{/privacy}",
    "received_events_url": "https://api.github.com/users/umihico/received_events",
    "type": "User",
    "site_admin": false
  },
  "body": null,
  "created_at": "2023-06-11T06:02:51Z",
  "updated_at": "2023-06-11T06:09:30Z",
  "closed_at": "2023-06-11T06:09:27Z",
  "merged_at": "2023-06-11T06:09:27Z",
  "merge_commit_sha": "dee03434a27cfa5a4d9ef5d29009aa70f4aa266a",
  "assignee": null,
  "assignees": [

  ],
  "requested_reviewers": [

  ],
  "requested_teams": [

  ],
  "labels": [

  ],
  "milestone": null,
  "draft": false,
  "commits_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/pulls/176/commits",
  "review_comments_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/pulls/176/comments",
  "review_comment_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/pulls/comments{/number}",
  "comments_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/issues/176/comments",
  "statuses_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/statuses/18734259bd9d920a13868f7692f88079b1876f50",
  "head": {
    "label": "umihico:feat/github-actions/2023-06-11",
    "ref": "feat/github-actions/2023-06-11",
    "sha": "18734259bd9d920a13868f7692f88079b1876f50",
    "user": {
      "login": "umihico",
      "id": 39179585,
      "node_id": "MDQ6VXNlcjM5MTc5NTg1",
      "avatar_url": "https://avatars.githubusercontent.com/u/39179585?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/umihico",
      "html_url": "https://github.com/umihico",
      "followers_url": "https://api.github.com/users/umihico/followers",
      "following_url": "https://api.github.com/users/umihico/following{/other_user}",
      "gists_url": "https://api.github.com/users/umihico/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/umihico/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/umihico/subscriptions",
      "organizations_url": "https://api.github.com/users/umihico/orgs",
      "repos_url": "https://api.github.com/users/umihico/repos",
      "events_url": "https://api.github.com/users/umihico/events{/privacy}",
      "received_events_url": "https://api.github.com/users/umihico/received_events",
      "type": "User",
      "site_admin": false
    },
    "repo": {
      "id": 346943840,
      "node_id": "MDEwOlJlcG9zaXRvcnkzNDY5NDM4NDA=",
      "name": "docker-selenium-lambda",
      "full_name": "umihico/docker-selenium-lambda",
      "private": false,
      "owner": {
        "login": "umihico",
        "id": 39179585,
        "node_id": "MDQ6VXNlcjM5MTc5NTg1",
        "avatar_url": "https://avatars.githubusercontent.com/u/39179585?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/umihico",
        "html_url": "https://github.com/umihico",
        "followers_url": "https://api.github.com/users/umihico/followers",
        "following_url": "https://api.github.com/users/umihico/following{/other_user}",
        "gists_url": "https://api.github.com/users/umihico/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/umihico/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/umihico/subscriptions",
        "organizations_url": "https://api.github.com/users/umihico/orgs",
        "repos_url": "https://api.github.com/users/umihico/repos",
        "events_url": "https://api.github.com/users/umihico/events{/privacy}",
        "received_events_url": "https://api.github.com/users/umihico/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/umihico/docker-selenium-lambda",
      "description": "The simplest demo of chrome automation by python and selenium in AWS Lambda",
      "fork": false,
      "url": "https://api.github.com/repos/umihico/docker-selenium-lambda",
      "forks_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/forks",
      "keys_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/teams",
      "hooks_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/hooks",
      "issue_events_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/issues/events{/number}",
      "events_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/events",
      "assignees_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/assignees{/user}",
      "branches_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/branches{/branch}",
      "tags_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/tags",
      "blobs_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/languages",
      "stargazers_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/stargazers",
      "contributors_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/contributors",
      "subscribers_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/subscribers",
      "subscription_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/subscription",
      "commits_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/contents/{+path}",
      "compare_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/merges",
      "archive_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/downloads",
      "issues_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/issues{/number}",
      "pulls_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/labels{/name}",
      "releases_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/releases{/id}",
      "deployments_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/deployments",
      "created_at": "2021-03-12T04:59:18Z",
      "updated_at": "2023-08-04T19:19:19Z",
      "pushed_at": "2023-07-14T01:59:29Z",
      "git_url": "git://github.com/umihico/docker-selenium-lambda.git",
      "ssh_url": "git@github.com:umihico/docker-selenium-lambda.git",
      "clone_url": "https://github.com/umihico/docker-selenium-lambda.git",
      "svn_url": "https://github.com/umihico/docker-selenium-lambda",
      "homepage": "",
      "size": 140,
      "stargazers_count": 306,
      "watchers_count": 306,
      "language": "Dockerfile",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": false,
      "has_discussions": false,
      "forks_count": 79,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 7,
      "license": {
        "key": "mit",
        "name": "MIT License",
        "spdx_id": "MIT",
        "url": "https://api.github.com/licenses/mit",
        "node_id": "MDc6TGljZW5zZTEz"
      },
      "allow_forking": true,
      "is_template": false,
      "web_commit_signoff_required": false,
      "topics": [
        "aws-lambda",
        "chromedriver",
        "chromium",
        "docker",
        "lambda",
        "python",
        "scraping",
        "selenium",
        "serverless"
      ],
      "visibility": "public",
      "forks": 79,
      "open_issues": 7,
      "watchers": 306,
      "default_branch": "main"
    }
  },
  "base": {
    "label": "umihico:main",
    "ref": "main",
    "sha": "0d4324fb494599fe35870c9a0c67bc4239e20c4f",
    "user": {
      "login": "umihico",
      "id": 39179585,
      "node_id": "MDQ6VXNlcjM5MTc5NTg1",
      "avatar_url": "https://avatars.githubusercontent.com/u/39179585?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/umihico",
      "html_url": "https://github.com/umihico",
      "followers_url": "https://api.github.com/users/umihico/followers",
      "following_url": "https://api.github.com/users/umihico/following{/other_user}",
      "gists_url": "https://api.github.com/users/umihico/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/umihico/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/umihico/subscriptions",
      "organizations_url": "https://api.github.com/users/umihico/orgs",
      "repos_url": "https://api.github.com/users/umihico/repos",
      "events_url": "https://api.github.com/users/umihico/events{/privacy}",
      "received_events_url": "https://api.github.com/users/umihico/received_events",
      "type": "User",
      "site_admin": false
    },
    "repo": {
      "id": 346943840,
      "node_id": "MDEwOlJlcG9zaXRvcnkzNDY5NDM4NDA=",
      "name": "docker-selenium-lambda",
      "full_name": "umihico/docker-selenium-lambda",
      "private": false,
      "owner": {
        "login": "umihico",
        "id": 39179585,
        "node_id": "MDQ6VXNlcjM5MTc5NTg1",
        "avatar_url": "https://avatars.githubusercontent.com/u/39179585?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/umihico",
        "html_url": "https://github.com/umihico",
        "followers_url": "https://api.github.com/users/umihico/followers",
        "following_url": "https://api.github.com/users/umihico/following{/other_user}",
        "gists_url": "https://api.github.com/users/umihico/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/umihico/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/umihico/subscriptions",
        "organizations_url": "https://api.github.com/users/umihico/orgs",
        "repos_url": "https://api.github.com/users/umihico/repos",
        "events_url": "https://api.github.com/users/umihico/events{/privacy}",
        "received_events_url": "https://api.github.com/users/umihico/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/umihico/docker-selenium-lambda",
      "description": "The simplest demo of chrome automation by python and selenium in AWS Lambda",
      "fork": false,
      "url": "https://api.github.com/repos/umihico/docker-selenium-lambda",
      "forks_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/forks",
      "keys_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/teams",
      "hooks_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/hooks",
      "issue_events_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/issues/events{/number}",
      "events_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/events",
      "assignees_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/assignees{/user}",
      "branches_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/branches{/branch}",
      "tags_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/tags",
      "blobs_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/languages",
      "stargazers_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/stargazers",
      "contributors_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/contributors",
      "subscribers_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/subscribers",
      "subscription_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/subscription",
      "commits_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/contents/{+path}",
      "compare_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/merges",
      "archive_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/downloads",
      "issues_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/issues{/number}",
      "pulls_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/labels{/name}",
      "releases_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/releases{/id}",
      "deployments_url": "https://api.github.com/repos/umihico/docker-selenium-lambda/deployments",
      "created_at": "2021-03-12T04:59:18Z",
      "updated_at": "2023-08-04T19:19:19Z",
      "pushed_at": "2023-07-14T01:59:29Z",
      "git_url": "git://github.com/umihico/docker-selenium-lambda.git",
      "ssh_url": "git@github.com:umihico/docker-selenium-lambda.git",
      "clone_url": "https://github.com/umihico/docker-selenium-lambda.git",
      "svn_url": "https://github.com/umihico/docker-selenium-lambda",
      "homepage": "",
      "size": 140,
      "stargazers_count": 306,
      "watchers_count": 306,
      "language": "Dockerfile",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": false,
      "has_discussions": false,
      "forks_count": 79,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 7,
      "license": {
        "key": "mit",
        "name": "MIT License",
        "spdx_id": "MIT",
        "url": "https://api.github.com/licenses/mit",
        "node_id": "MDc6TGljZW5zZTEz"
      },
      "allow_forking": true,
      "is_template": false,
      "web_commit_signoff_required": false,
      "topics": [
        "aws-lambda",
        "chromedriver",
        "chromium",
        "docker",
        "lambda",
        "python",
        "scraping",
        "selenium",
        "serverless"
      ],
      "visibility": "public",
      "forks": 79,
      "open_issues": 7,
      "watchers": 306,
      "default_branch": "main"
    }
  },
  "_links": {
    "self": {
      "href": "https://api.github.com/repos/umihico/docker-selenium-lambda/pulls/176"
    },
    "html": {
      "href": "https://github.com/umihico/docker-selenium-lambda/pull/176"
    },
    "issue": {
      "href": "https://api.github.com/repos/umihico/docker-selenium-lambda/issues/176"
    },
    "comments": {
      "href": "https://api.github.com/repos/umihico/docker-selenium-lambda/issues/176/comments"
    },
    "review_comments": {
      "href": "https://api.github.com/repos/umihico/docker-selenium-lambda/pulls/176/comments"
    },
    "review_comment": {
      "href": "https://api.github.com/repos/umihico/docker-selenium-lambda/pulls/comments{/number}"
    },
    "commits": {
      "href": "https://api.github.com/repos/umihico/docker-selenium-lambda/pulls/176/commits"
    },
    "statuses": {
      "href": "https://api.github.com/repos/umihico/docker-selenium-lambda/statuses/18734259bd9d920a13868f7692f88079b1876f50"
    }
  },
  "author_association": "OWNER",
  "auto_merge": null,
  "active_lock_reason": null,
  "merged": true,
  "mergeable": null,
  "rebaseable": null,
  "mergeable_state": "unknown",
  "merged_by": {
    "login": "umihico",
    "id": 39179585,
    "node_id": "MDQ6VXNlcjM5MTc5NTg1",
    "avatar_url": "https://avatars.githubusercontent.com/u/39179585?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/umihico",
    "html_url": "https://github.com/umihico",
    "followers_url": "https://api.github.com/users/umihico/followers",
    "following_url": "https://api.github.com/users/umihico/following{/other_user}",
    "gists_url": "https://api.github.com/users/umihico/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/umihico/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/umihico/subscriptions",
    "organizations_url": "https://api.github.com/users/umihico/orgs",
    "repos_url": "https://api.github.com/users/umihico/repos",
    "events_url": "https://api.github.com/users/umihico/events{/privacy}",
    "received_events_url": "https://api.github.com/users/umihico/received_events",
    "type": "User",
    "site_admin": false
  },
  "comments": 0,
  "review_comments": 0,
  "maintainer_can_modify": false,
  "commits": 2,
  "additions": 26,
  "deletions": 0,
  "changed_files": 2
}`);

describe('parser', () => {
  it('Returns data and raw', () => {
    expect(parseRawData(demoData)).toStrictEqual({
      data: {
        additions: 26,
        changedFiles: 2,
        commitCount: 2,
        deletions: 0,
        mergedAt: '2023-06-11T06:09:27Z',
        repo: 'docker-selenium-lambda',
        title: 'Add demo-test GitHub action',
        url: 'https://github.com/umihico/docker-selenium-lambda/pull/176',
        user: 'umihico',
      },
      row: [
        '2023-06-11T06:09:27Z',
        'docker-selenium-lambda',
        'umihico',
        'Add demo-test GitHub action',
        'https://github.com/umihico/docker-selenium-lambda/pull/176',
        '2',
        '2',
        '26',
        '0',
      ],
    });
  });
});
